Repository brevia-ai/brevia-bedita, pull requests merged in 2024-03, with the labels that each got.

#7 Handle links to web pages in Brevia collection index
  src/Event/BreviaEventHandler.php
  src/Index/CollectionHandler.php
  tests/TestMockTrait.php
Labels: enhancement, release:minor

#3 BEdita Core and Api 5.15
  composer.json
Labels: enhancement, release:patch

#10 Add URL in links metadata
  src/Index/CollectionHandler.php
Labels: release:patch
